// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TungSon.Migrations
{
    [DbContext(typeof(NTSContext))]
    [Migration("20211215041011_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TungSon.NTS", b =>
                {
                    b.Property<string>("NTSID")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NTSname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("NTSID");

                    b.ToTable("NTS");
                });
#pragma warning restore 612, 618
        }
    }
}
